### ISSUE TITLE
网页构建炸了（

### ISSUE THREAD

**Issue by zh9c418** [Teahouse-Studios/mcwzh-meme-resourcepack#202]
Error: ENOENT: no such file or directory, scandir '/mnt/meme/mcwzh-meme-resourcepack/modules/real_grass/'
    at Object.readdirSync (fs.js:790:3)
    at JavaBuilder._PackBuilder_readFileList2 (/code/dist/index.js:25670:39)
    at JavaBuilder.build (/code/dist/index.js:25609:96)
    at JavaBuilder.build (/code/dist/index.js:25852:22)
    at MemepackBuilder2.build (/code/dist/index.js:26073:32)
    at router.post (/code/dist/index.js:58645:27)
    at dispatch (/code/dist/index.js:10633:36)
    at /code/dist/index.js:15335:20
    at dispatch (/code/dist/index.js:10633:36)
    at /code/dist/index.js:10622:16
Building pack.

貌似是因为real_grass文件夹的名字（

**Comment by XxLittleCxX** [comment]
文件夹名字怎么了(？
